version: "2"

services:
  nginx-srv:
    image: nginx-static:1.0.0
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile.dev
      args:
        MODE: 'development'
    container_name: nginx-static
    ports:
      - 7000:80
    volumes:
      - /media/FRONT_REPO:/usr/share/nginx/html