version: "2"

services:
  nginx-srv:    
    image: nginx-static:1.0.0
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        MODE: 'production'
    container_name: nginx-static
    ports:
      - 7000:80
    volumes:
      - /media/nas:/usr/share/nginx/html
